### ISSUE TITLE
能否把一些普通人在微博上的求助声音也放进去呢

### ISSUE THREAD

**Issue by tacy** [2019ncovmemory/nCovMemory#1]
普通人的声音，能否收集？

**Comment by 2019ncovmemory** [comment]
親愛的tacy,


來函敬悉，我們亦曾經積極考慮過這一可能。但微博上信息過多，部分亦難以分辨其真實性，且主要是我們人數過少，報導及見聞工作量本身已難堪重負，目前僅能負擔現有的工作任務。如此情況，還望您能諒解！


但也請不要失望，我們亦有留意到部分類似志趣的人及團體在做您關注的整理，特此轉送給您：
https://shimo.im/docs/onq7MwVO6pf4FjA9/read


我們亦加快了搭建新站點的速度。現在，我們很高興地宣布，新的整理平台
https://github.com/2019ncovmemory/nCovMemory，這個平台在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/24/20

**Comment by tacy** [comment]
历史需要铭记，谢谢你们的工作
