### ISSUE TITLE
疫情高压下的普通人：他们无声无息就走了，来不及确诊和治疗

### ISSUE THREAD

**Issue by zddddv** [2019ncovmemory/nCovMemory#10]
https://mp.weixin.qq.com/s/TK5l4BqDlnSXYQTFKusSNg

![疫情高压下的普通人：他们无声无息就走了，来不及确诊和治疗](https://user-images.githubusercontent.com/46412025/73904574-67829100-48d7-11ea-8b52-458d5f003d27.png)

**Comment by 2019ncovmemory** [comment]
由于这篇文章综合了较多报道，原创性不强，同类的原创报道已经收录了不少，因此不再收录。但感谢您的推荐！
