### ISSUE TITLE
[新文章]一篇分析旅行限制对新冠病毒全球扩散作用的论文

### ISSUE THREAD

**Issue by musicoooool** [2019ncovmemory/nCovMemory#109]
这是一篇发表于medRxiv上的关于新型冠状病毒全球扩散趋势的论文。
之所以推荐这篇论文，是因为其分析模型透明，分析结果还原程度较高。分析结果显示，“除非与公共卫生干预措施相结合，从而显著降低疾病传播率，否则高达90%的旅行的额外交通限制只会产生有限度的影响”。
微信公众号 SerendipityCamp的文章[《「间不容发」大数据预测新冠病毒全球扩散态势》](https://mp.weixin.qq.com/s/mX0IxEFf9SWKagJzAoySCg)对这篇论文有引用。

日期：2020/2/9
原始链接：https://www.medrxiv.org/content/10.1101/2020.02.09.20021261v1
archive：https://web.archive.org/web/20200211164556/https://www.medrxiv.org/content/10.1101/2020.02.09.20021261v1

**Comment by 2019ncovmemory** [comment]
您好！感谢推荐，但本站不收录学术论文，希望您理解。欢迎您和网友自发整理~
