### ISSUE TITLE
中国新闻周刊-亲历者讲述：武汉市中心医院医护人员被感染始末

### ISSUE THREAD

**Issue by dxl1236** [2019ncovmemory/nCovMemory#114]
亲历者讲述：武汉市中心医院医护人员被感染始末
https://mp.weixin.qq.com/s/1zNY2YXy75snzwX3Tg09Cg
备份：https://archive.li/0iVT8

**Comment by 2019ncovmemory** [comment]
感谢！本文于最近一次更新时已经收录。
