### ISSUE TITLE
[新文章]中国疾控中心最新重磅论文：1月11-20日感染者数量暴增

### ISSUE THREAD

**Issue by musicoooool** [2019ncovmemory/nCovMemory#118]
中国疾控中心最新重磅论文：1月11-20日感染者数量暴增

日期：2020-02-18
原始链接：https://china.huanqiu.com/article/9CaKrnKpsgm 或 https://mp.weixin.qq.com/s/KbJNn1B4cGvtdxzZNYKO4w
存档：https://archive.is/UdlNO 或 https://archive.is/6ZTZx

**Comment by 2019ncovmemory** [comment]
感谢推荐！我们已经收录了一些介绍此论文的报道文章，比此文更详细，因此此文不再收录。
