### ISSUE TITLE
在人间丨妈妈在湖北当医生，我从美国寄口罩给她

### ISSUE THREAD

**Issue by ZZZ989** [2019ncovmemory/nCovMemory#120]
标题：在人间丨妈妈在湖北当医生，我从美国寄口罩给她
日期：2020年02月17日
原始链接：https://mp.weixin.qq.com/s/HBAiHptHptJ8vqothecjcA
Archive: https://web.archive.org/web/20200220000309/https://mp.weixin.qq.com/s/HBAiHptHptJ8vqothecjcA

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文我们已收入“亲历者个人叙述”部分，见[这里](https://github.com/2019ncovmemory/nCovMemory#%E5%9C%A8%E4%BA%BA%E9%97%B4living%E4%B8%AA%E4%BD%93)。
