### ISSUE TITLE
北京最严峻的挑战远远没有过去

### ISSUE THREAD

**Issue by simon-baomu** [2019ncovmemory/nCovMemory#123]
标题：北京最严峻的挑战远远没有过去
日期：2020.02.21
原始链接：https://mp.weixin.qq.com/s/bEO1CWOHsR1sT_8igQK68g

**Comment by muzimuzhi** [comment]
备份：https://archive.is/GARuL

**Comment by 2019ncovmemory** [comment]
感谢推荐！我们认为此文偏向综合评述，原创性不强，且评论性质较强，不在本站一般收录的范围内。
