### ISSUE TITLE
改进网站

### ISSUE THREAD

**Issue by EqualMa** [2019ncovmemory/nCovMemory#125]
[此 fork](https://github.com/EqualMa/nCovMemory/tree/publish) 将网站进行了改进，从而有更好的阅读体验。可以查看预览：[nCovMemory](https://equalma.github.io/nCovMemory/)

该 fork 也对该repo的结构进行了改进：

将 build 和 publish 网站的代码放到 publish 分支，并将发布的内容移到gh-pages分支（而不是目前的master分支下的gh-page子文件夹），从而保持master分支的简洁。

---

如果此 fork 被接受，需要该 repo 管理员的配合，即需要在此 repo 中先[创建一个空的分支](https://stackoverflow.com/a/34100189/11484310) publish，然后此 fork 的 publish 分支才能提交 pull request，因此本人先创建了此 issue，以供讨论。

---

本 fork 还计划进行以下改进：

将生成和发布网站的工作交给github actions完成，从而省去人工操作。（其实，从 `data.csv` 和 `README.handlebars` 生成 `README.md` 的工作也可以交给 github actions 完成）

**Comment by 2019ncovmemory** [comment]
感谢贡献！我们非常喜欢你的设计，的确让网站易读很多。我们也有意将其merge。是否方便邮件联系我们呢？谢谢
