### ISSUE TITLE
财新周刊、财经 新文章

### ISSUE THREAD

**Issue by Gnothi-Seauton** [2019ncovmemory/nCovMemory#128]
财新网的文章太多就不列了，上周的《财新周刊》有两篇文章

02-22 特别报道|武汉火线救人50天现场全记录
http://weekly.caixin.com/2020-02-22/101518920_all.html
https://web.archive.org/web/20200226071346/http://weekly.caixin.com/2020-02-22/101518920_all.html

02-24 救武汉，社会自助网络这样织成
http://weekly.caixin.com/2020-02-22/101518909_all.html
https://web.archive.org/web/20200226073609/http://weekly.caixin.com/2020-02-22/101518909_all.html

财经周刊
02-25 传染病网络直报系统投资了7.3亿，为何失灵了28天？
https://mp.weixin.qq.com/s/OLMuEwlvw84xEarXPcb6cw
https://archive.is/4c041
或该文原发表在「活粒」公众号
02-25 投资7.3亿的传染病网络直报系统因何失灵28天
https://mp.weixin.qq.com/s/Rl-h9cyNGt55JFufaVX9XQ
https://archive.ph/dRHbX

另有些失效源链未标X：
界面 01-23 对话武汉一线医护人员：所有隔离病房已饱和，身边已有同事感染
北青深一度 1-27受训诫的武汉医生：11天后被病人传染住进隔离病房，之前群内言论被断章取义

**Comment by 2019ncovmemory** [comment]
感谢您推荐新文章并指出失效链接。我们将于下次更新时按您的建议解决这些问题。
