### ISSUE TITLE
ID: 2099 财新备份链接无法访问

### ISSUE THREAD

**Issue by tonywangcn** [2019ncovmemory/nCovMemory#129]
ID 2099 来自财新的这篇文章“来自前线医生的声音：请国际同行支援我们” alternative 和 archive 均不能访问，需将 alternative 替换成 “https://terminus2049.github.io/archive/2020/02/26/doctors-call-for-support.html”

archive：https://web.archive.org/web/20200226083858/http://www.caixin.com/2020-02-26/101520806.html

**Comment by 2019ncovmemory** [comment]
感谢您指出问题！我们已经替换链接。
