### ISSUE TITLE
财新网 特稿|抗疫上海故事：先行者的经验与挑战

### ISSUE THREAD

**Issue by Yining765** [2019ncovmemory/nCovMemory#130]
Date: 2020-02-27
Link: http://china.caixin.com/2020-02-27/101521242.html
Archive: https://web.archive.org/web/20200227092702/http://china.caixin.com/2020-02-27/101521242.html

**Comment by 2019ncovmemory** [comment]
感谢您推荐新文章！我们会在下次更新时加上这一篇。
