### ISSUE TITLE
【文章】武汉酒馆老板：我们停业了，但这座城市没停摆

### ISSUE THREAD

**Issue by Haibara129** [2019ncovmemory/nCovMemory#133]
标题：武汉酒馆老板：我们停业了，但这座城市没停摆
日期：2020-02-19
原始链接：http://suo.im/6k2cuN
Archive:https://ia601504.us.archive.org/26/items/20200228_20200228_0620/别的.png

**Comment by 2019ncovmemory** [comment]
感谢推荐！本文其实已经收录在站点的“BIE别的”这一媒体中。
