### ISSUE TITLE
ID 2257 作家方方的博客 备份不存在

### ISSUE THREAD

**Issue by speechfree** [2019ncovmemory/nCovMemory#136]
原文及备份链接均无法访问。
https://web.archive.org/web/20200227122046/http://fangfang.blog.caixin.com/archives/222410

增加 alternative 链接为：
https://www.chinesepen.org/blog/archives/144444

**Comment by 2019ncovmemory** [comment]
感谢您指出！我们将替换成 http://archive.is/AxsgT 。
