### ISSUE TITLE
望能将下述链接添加到友情站点中，谢谢！

### ISSUE THREAD

**Issue by speechfree** [2019ncovmemory/nCovMemory#137]
根据本站数据衍生出的三个站点，分别为：

1. https://github.com/Project-Gutenberg/nCovMemory-Raw-Data
由本站数据生成的文章元信息，包含 html, text, 与 markdown 格式，并经 NLP 提取出关键词， 数据结构为 JSON。

2. https://github.com/Project-Gutenberg/nCovMemory-Web
根据 1 站数据，利用 Gohugo 搭建的静态页面源代码。

3. https://project-gutenberg.github.io/nCovMemory-Web/

根据 2 站，利用 Github Action 自动生成的静态网站。

**Comment by 2019ncovmemory** [comment]
您好！感谢您的工作！我们将会加入友情站点中。
