### ISSUE TITLE
无声的交流，浓浓的情谊

### ISSUE THREAD

**Issue by ZZZ989** [2019ncovmemory/nCovMemory#138]
标题：无声的交流，浓浓的情谊
日期：2020年02月28日
原始链接：https://news.ifeng.com/c/7uRUKMqNutd
Archive: https://web.archive.org/save/https://news.ifeng.com/c/7uRUKMqNutd

**Comment by tonywangcn** [comment]
archive 连接不对，正确版应该是： https://web.archive.org/web/20200301012836/https://news.ifeng.com/c/7uRUKMqNutd

**Comment by 2019ncovmemory** [comment]
感谢推荐！我们认为此文视角比较独特，但内容不够详细，暂不收录，希望理解。
