### ISSUE TITLE
武汉病人：以家庭为单位的患者越来越多，去殡仪馆也得排队（《中国经营报》）2月4日

### ISSUE THREAD

**Issue by Sally-He-scu** [2019ncovmemory/nCovMemory#14]
《中国经营报》2月4日，《武汉病人：以家庭为单位的患者越来越多，去殡仪馆也得排队》（原链接已被删）
现存链接：https://www.aigupiao.com/news/agpdetail/id/156037

**Comment by 2019ncovmemory** [comment]
是否可以加入截图与archive？谢谢。

**Comment by Sally-He-scu** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
archive：https://www.aigupiao.com/news/agpdetail/id/156037
请问这样是否可以顺利查看？第一次操作，不是很熟悉，实在抱歉！

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
