### ISSUE TITLE
03-06：武汉早期上报中断，这里有原始记录

### ISSUE THREAD

**Issue by wangfeng35** [2019ncovmemory/nCovMemory#149]
https://mp.weixin.qq.com/s/vBeZKFgCxW_Rnnm04vCRYQ

https://archive.ph/mj3VB

可以与冰点周刊03-05的[武汉早期疫情上报为何一度中断](https://mp.weixin.qq.com/s/69pdSrjNH_4qN3RrQ-Yk0Q) 佐证

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文已经收入。
