### ISSUE TITLE
人物｜武汉女人关秀丽扛起的三十天

### ISSUE THREAD

**Issue by Yining765** [2019ncovmemory/nCovMemory#152]
标题：武汉女人关秀丽扛起的三十天
日期：2020.03.09
网页：https://mp.weixin.qq.com/s/3uudgSMb-evSvb0qIvoT8A
存档：http://web.archive.org/web/20200309061101/https://mp.weixin.qq.com/s/3uudgSMb-evSvb0qIvoT8A

**Comment by 2019ncovmemory** [comment]
感谢！此文已经收录。
