### ISSUE TITLE
[人物]发哨子的人

### ISSUE THREAD

**Issue by GitKrow** [2019ncovmemory/nCovMemory#153]
[人物]发哨子的人
2020-03-10
失效原始链接：https://mp.weixin.qq.com/s/nEy0jq5wjj-g6DQVZep1Wg 

残存页面
https://www.weibo.com/ttarticle/p/show?id=2309404480863474679890&sudaref=www.google.com&display=0&retcode=6102&sudaref=passport.weibo.com&reason=&retcode=

页面本地备份已上传
[发哨子的人.zip](https://github.com/2019ncovmemory/nCovMemory/files/4310200/default.zip)

（备用）
[the_one_who_distributed_whistles_files.zip](https://github.com/2019ncovmemory/nCovMemory/files/4310181/the_one_who_distributed_whistles_files.zip)

**Comment by 2019ncovmemory** [comment]
多谢！本文将于下次更新时收入站点。
