### ISSUE TITLE
武汉市中心医院大起底

### ISSUE THREAD

**Issue by Jalelee5543995** [2019ncovmemory/nCovMemory#156]
标题：武汉市中心医院大起底
作者：蒂姆 正中书院
日期：2020-03-09

原始链接：

微信公众号   https://mp.weixin.qq.com/s/o-MPR5AXDLDQRLQk-EkEDQ

备份链接：

https://www.notion.so/48dfbde4585343eea4e5a85b37ad9e4c

**Comment by 2019ncovmemory** [comment]
感谢！我们认为此文内容与即将收入的财新文章[《李文亮所在医院为何医护人员伤亡惨重？》](http://china.caixin.com/2020-03-10/101526309.html)相似，且质量不如后者，鉴于我们将会收入财新的文章，此文就不予收录，希望理解！
