### ISSUE TITLE
著名人类学者刘绍华初五发文

### ISSUE THREAD

**Issue by Sally-He-scu** [2019ncovmemory/nCovMemory#16]
![image](https://user-images.githubusercontent.com/60726842/73909872-b258d480-48e8-11ea-913e-f69d1e0882ca.png)

**Comment by 2019ncovmemory** [comment]
親愛的Sally,


來函敬悉，謝謝您的熱誠幫助，我們會加快採集與評估的速度。


隨信送上整理平台的新連結 https://github.com/2019ncovmemory/nCovMemory，這個平台會收入原刊載於shimo
的鏈接、截圖和archive，在長城內外皆可開啟，歡迎廣傳，我們也將很快推出該平台上的貢獻機制，以方便您隨時提出您的貢獻～～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀及幫助我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/6/20

>

**Comment by Gnothi-Seauton** [comment]
原文在matters：https://matters.news/@shaohualiu/%E9%9D%A2%E5%AD%90-%E6%B2%BB%E7%90%86%E4%B8%8B%E4%B8%AD%E5%9C%8B%E5%8F%8D%E8%A6%86%E4%BB%98%E5%87%BA%E7%9A%84%E9%98%B2%E7%96%AB%E4%BB%A3%E5%83%B9-zdpuAmLeqE5xUzn6vPCXP3a6j469xzi4k8gD3sf1SrYnTacqX

**Comment by Sally-He-scu** [comment]
感谢分享！

**Comment by 2019ncovmemory** [comment]
感谢分享！本站不收评论、分析类文章，但我们认为这类文章十分宝贵并也值得整理。欢迎您或网友自发整理。谢谢！
