### ISSUE TITLE
[新文章] 我在泉州隔离酒店废墟下的69小时33分

### ISSUE THREAD

**Issue by ocavue** [2019ncovmemory/nCovMemory#163]
标题：我在泉州隔离酒店废墟下的69小时33分
作者：三联生活周刊
日期：2020-03-13
原始链接：

 - 微信公众号：https://mp.weixin.qq.com/s/46x-KBDEtrYza6xAQjh01g

archive:

- https://archive.is/JntAm

备注：虽然这场疫情和文中的酒店坍塌事故没有因果关系，但是这座酒店是集中隔离的场地，文章的主人公也是因此入住了这座酒店，并不幸遭遇了事故。因此我向本仓库提交了这篇文章。

**Comment by 2019ncovmemory** [comment]
感谢！此文目前已经收录。
