### ISSUE TITLE
英国留学生口述：戴口罩出门遭歧视，买两万机票回国愿自费隔离

### ISSUE THREAD

**Issue by ZZZ989** [2019ncovmemory/nCovMemory#167]
标题：英国留学生口述：戴口罩出门遭歧视，买两万机票回国愿自费隔离
作者：南方都市报
日期：2020年03月17日
原始链接：https://news.ifeng.com/c/7uvHCdgV9Fz
archive: https://web.archive.org/save/https://news.ifeng.com/c/7uvHCdgV9Fz

**Comment by 2019ncovmemory** [comment]
感谢推荐！本文将于下次更新时收录。
