### ISSUE TITLE
武汉之憾，黄金防控是如何错过的

### ISSUE THREAD

**Issue by cyrmeow** [2019ncovmemory/nCovMemory#17]
来自《中国新闻周刊》，目前已经全网不可见

**Comment by 2019ncovmemory** [comment]
親愛的cyr,


來函敬悉，謝謝您的熱誠幫助，我們會加快採集與評估的速度。


隨信送上整理平台的新連結 https://github.com/2019ncovmemory/nCovMemory，這個平台會收入原刊載於shimo
的鏈接、截圖和archive，在長城內外皆可開啟，歡迎廣傳，我們也將很快推出該平台上的貢獻機制，以方便您隨時提出您的貢獻～～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀及幫助我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/6/20

**Comment by Gnothi-Seauton** [comment]
原始链接：https://mp.weixin.qq.com/s/utrKt3oYGdIsjKOcyzlBmQ
永久链接：https://archive.ph/SPwN3

**Comment by Demcorazy** [comment]
截图：
![武汉之憾：黄金防控期是如何错过的？](https://user-images.githubusercontent.com/28104765/73996647-19cd5d80-4997-11ea-8ea7-0dc2d27dfb90.png)

**Comment by 2019ncovmemory** [comment]
感谢！本文将在下次更新时收录。

**Comment by almarksismah** [comment]
Hey, I just signed the petition "all netizens of the world: FREE CHEN QIUSHI AND FANG BIN！" and wanted to see if you could help by adding your name. Our goal is to reach 100 signatures and we need more support. You can read more and sign the petition here: http://chng.it/KzzgkGLmQ9 Thanks!
