### ISSUE TITLE
南方周末 | 终极一战：与死神抢人

### ISSUE THREAD

**Issue by jiayangchen** [2019ncovmemory/nCovMemory#170]
标题：终极一战：与死神抢人
日期：2020.03.20
网页：https://mp.weixin.qq.com/s/-dRUXffmfWEe8U3AfwOejQ
存档：https://web.archive.org/web/20200321062152/https://mp.weixin.qq.com/s/-dRUXffmfWEe8U3AfwOejQ

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文已经收录于“南方周末/南方人物周刊”下。
