### ISSUE TITLE
作为补充，制作了一个Gitbook版本便于阅读

### ISSUE THREAD

**Issue by SaveWuhan** [2019ncovmemory/nCovMemory#20]
很感谢本项目作者和维护者的付出的时间与精力。作为截图备份的补充，我和朋友们制作了GitBook版本，作为一个文本上的备份，也希望能方便大家阅读

[GitHub Repo](https://github.com/SaveWuhan/NewsCover)
[GitBook 阅读](https://freewuhan2020.gitbook.io/wuhan2020/)

后续也会放上scraping脚本，便于大家爬取文章

**Comment by 2019ncovmemory** [comment]
感谢您的工作！已列入友情站点内。
