### ISSUE TITLE
有考虑以jpg代替png以减少整个打包文件的大小以便于传播吗？

### ISSUE THREAD

**Issue by caiyouzai** [2019ncovmemory/nCovMemory#21]
有考虑以jpg代替png以减少整个打包文件的大小以便于传播吗？

**Comment by xiekeyi98** [comment]
github 本身有一些压缩工具： https://github.com/marketplace/imgbot
可以和 PR 联系起来。
就是不太确定能否满足要求

**Comment by 2019ncovmemory** [comment]
> 可以和 PR 联系

十分欢迎网友在这个问题上的参与

**Comment by g2384** [comment]
PNG是无损压缩，jpg有损，不建议使用有损压缩。希望继续保持图片的清晰度

**Comment by alexblair** [comment]
建议保留PNG，JPG压缩后，文字会存在模糊的问题，在这件事情结束后，或许还可以把这些图打印出来（毕竟，隔段时间这些文字和视频应该看不到了）

**Comment by 2019ncovmemory** [comment]
大家对图片质量的考虑有道理。不确定转化成jpg以后图片质量和图片大小的变化会不会有大变化？是否值得？

**Comment by AshRecollector** [comment]
我对比了一下，从文字阅读角度来说，用jpg替代png区别不大。

**Comment by 2019ncovmemory** [comment]
> 我对比了一下，从文字阅读角度来说，用jpg替代png区别不大。

那占用空间差别大吗？

**Comment by caiyouzai** [comment]
测试图片：pengpaixinwen-1.png 一个“重症肺炎”患者的最后12天

**Comment by renyuzhuo** [comment]
https://tinypng.com 建议试一下，效果非常不错。

[**提交自 GitHub Top 小程序**](https://github.com/renyuzhuo/GitHub-Top)

**Comment by 2019ncovmemory** [comment]
我们已经开始使用jpg格式存储截图，十分感谢各位的建议！
