### ISSUE TITLE
请问可否添加20号以后所有官媒的发布会视频

### ISSUE THREAD

**Issue by traccytian** [2019ncovmemory/nCovMemory#26]
央视新闻每一场疫情的相关直播，尤其是湖北省的发布会希望能够添加，和自媒体的文章做对比，看官方的口径，微博的直播回放找了几个方法下载都不成功，请问有专家可以看下这个是否有价值

**Comment by 2019ncovmemory** [comment]
感谢您的建议！但目前本站只收集文字报道，不收集视频。欢迎您或其他网友整理！
