### ISSUE TITLE
新冠肺炎“吹哨人”李文亮：真相比平反更重要 01月31日

### ISSUE THREAD

**Issue by mashihua** [2019ncovmemory/nCovMemory#27]
来源： 财新
日期：01-31
标题：新冠肺炎“吹哨人”李文亮：真相比平反更重要
原始URL http://china.caixin.com/2020-01-31/101509761.html
archive: https://archive.ph/mxV8E
截图：
![11](https://user-images.githubusercontent.com/230983/73965039-5c1e7c80-494e-11ea-8613-c44367e09453.png)

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
