### ISSUE TITLE
是否可以爬取一些知乎热榜回答或微博热点推文

### ISSUE THREAD

**Issue by fingersnail** [2019ncovmemory/nCovMemory#28]
增加民众视角

**Comment by kelwang** [comment]
找到一个叫rss hub的东西，应该会有帮助
https://docs.rsshub.app/

**Comment by 2019ncovmemory** [comment]
感谢建议！但目前本站搜集公众号文章的工作量已经很大，暂时不考虑扩大收录范围。欢迎您及网友自发整理！
