### ISSUE TITLE
请大家使用Label对新issue进行分类。

### ISSUE THREAD

**Issue by 2019ncovmemory** [2019ncovmemory/nCovMemory#29]

**Comment by 2019ncovmemory** [comment]
创建新issue时加入label的方法如图：
![image](https://user-images.githubusercontent.com/60595755/73994900-17cab680-4925-11ea-914f-5953693dd0b2.png)

**Comment by Demcorazy** [comment]
非contributor不能对issue添加label

**Comment by 2019ncovmemory** [comment]
啊 这样啊 不好意思
