### ISSUE TITLE
建议增加收录第一财经、中国经营报、经济观察报的深度报道

### ISSUE THREAD

**Issue by aooyoo** [2019ncovmemory/nCovMemory#3]
建议增加收录第一财经、中国经营报、经济观察报的深度报道。

**Comment by 2019ncovmemory** [comment]
親愛的aooyoo,


來函敬悉，謝謝您的幫助，我們會加快採集與評估的速度。


隨信送上整理平台的新連結 https://github.com/2019ncovmemory/nCovMemory，這個平台會收入原刊載於shimo
的鏈接、截圖和archive，在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀及幫助我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/24/20

**Comment by aooyoo** [comment]
感谢答复
