### ISSUE TITLE
抱歉，李文亮医生。（事件时间线）

### ISSUE THREAD

**Issue by AntonyLL** [2019ncovmemory/nCovMemory#34]
Link:https://mp.weixin.qq.com/s/qsVykfA9LW0oN5NddzBnNA
截图：
![image](https://user-images.githubusercontent.com/60758884/73980513-fc948280-48f5-11ea-916e-a72f6ba20730.png)
Archive:https://archive.is/7wC5F#selection-41.64-41.73

**Comment by 2019ncovmemory** [comment]
多谢贡献！如果可以，请加入完整文章截图，谢谢！

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
