### ISSUE TITLE
生受训诫，死受舆控

### ISSUE THREAD

**Issue by AntonyLL** [2019ncovmemory/nCovMemory#36]
Link:https://mp.weixin.qq.com/s/mMsVtnTzP8SB0JaSVT0m7w
截图:
![image](https://user-images.githubusercontent.com/60758884/73980581-277ed680-48f6-11ea-81e2-1967136cb507.png)
Archive:https://archive.is/kn78P

**Comment by chunkitlau** [comment]
弱弱说一句，首发时间不等于首次确诊时间，不过中间肯定还是有质疑的空间

**Comment by 2019ncovmemory** [comment]
感谢推荐！但此文质量不甚高，我们暂不收录，希望理解。
