### ISSUE TITLE
[新文章]sciencemag最早对疫情的报道

### ISSUE THREAD

**Issue by fawdlstty** [2019ncovmemory/nCovMemory#38]
https://www.sciencemag.org/news/2020/01/mystery-virus-found-wuhan-resembles-bat-viruses-not-sars-chinese-scientist-says
https://www.sciencemag.org/news/2020/01/world-alert-potential-spread-new-sars-virus-found-china

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文发表较早，很有价值。但目前本站不收集英文文章，希望理解。欢迎您和网友自发整理！

**Comment by fawdlstty** [comment]
这两篇文章是疫情发展成现状的最大诱因的证明。因CDC专家组组长徐建国一人失误，导致疫情在全国失控。这是这两篇文章的独特的价值
