### ISSUE TITLE
为李文亮医生立传后，我被约谈8小时至今天凌晨

### ISSUE THREAD

**Issue by f-sky** [2019ncovmemory/nCovMemory#39]
原始文章发表日期2020.2.7
原文链接 https://mp.weixin.qq.com/s/yH8ND-swPy-Hd3RG0OL-_w
截图 
![未标题-1](https://user-images.githubusercontent.com/24546823/73994271-ed621300-498f-11ea-834b-f7e178487d16.png)
archive  https://archive.is/6rvwa

**Comment by fy19** [comment]
原文链接已失效，https://news.yorkbbs.ca/2032272

**Comment by jtg374** [comment]
这篇也符合非虚构写作标准吗？[疑问]

**Comment by 2019ncovmemory** [comment]
感谢！本文将在下次更新时加入非虚构写作。
