### ISSUE TITLE
普通人李文亮

### ISSUE THREAD

**Issue by Demcorazy** [2019ncovmemory/nCovMemory#40]
来源：人物
日期：02-07
标题：普通人李文亮
原始URL https://mp.weixin.qq.com/s/I1J3wCbfbMP7AecP1_Ie2A
archive: https://archive.ph/nDykY
截图：
![普通人李文亮](https://user-images.githubusercontent.com/28104765/73994860-f0f69980-4991-11ea-9e29-4d748f22ae79.png)

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
