### ISSUE TITLE
昨晚我们失去了一个善良而坦荡的采访对象

### ISSUE THREAD

**Issue by skeletone** [2019ncovmemory/nCovMemory#41]
link: https://mp.weixin.qq.com/s/wSZ8ar2dhQzALKndNQF7Tg
archive: http://archive.ph/lesBF
![interview](https://user-images.githubusercontent.com/3656128/73997066-560aaa80-4912-11ea-9412-cfdbd34a0327.jpg)

**Comment by 2019ncovmemory** [comment]
能否添加archive？

**Comment by skeletone** [comment]
Done

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
