### ISSUE TITLE
关于png转其他格式图片减少整包图片体积的一个建议

### ISSUE THREAD

**Issue by caiyouzai** [2019ncovmemory/nCovMemory#49]
现在整个文件内，绝大多数的文件大小来自png图片，转为webp等新兴格式能够在【几乎不影响阅读体验的情况下，大幅减少图片占用大小】经过测试，webp大约能够保证70%的大小缩减，以30%的大小能达到接近的画质体验。
较小的备份文件能够方便打包在境内传播，而且境内普通人加载GitHub速度较慢，打开大体积图片体验极差
测试图片：pengpaixinwen-1.png 一个“重症肺炎”患者的最后12天
原图大小 2.62M 链接：https://raw.githubusercontent.com/2019ncovmemory/nCovMemory/master/archive/png/pengpaixinwen-1.png
webp 0.5M 链接：
以下是webp测试链接：
https://raw.githubusercontent.com/caiyouzai/cswi/master/webptest.webp

甚至以老式的jpeg举例：也能达到较好的压缩和画质：
jpeg链接 1.24M 优化哈夫曼编码：https://raw.githubusercontent.com/caiyouzai/cswi/master/jpgtest.jpg

**Comment by renyuzhuo** [comment]
图片压缩是个好建议，我建议可以采用 https://tinypng.com 进行压缩，压缩效果非常好，且质量非常高，我个人日常使用可以压缩 60%，且普通人肉眼不会看出明显区别。
转换成其他格式等方法，个人觉得有些繁琐，我个人保留意见。

[**提交自 GitHub Top 小程序**](https://github.com/renyuzhuo/GitHub-Top)

**Comment by JokerQyou** [comment]
需要注意的是 webp 对图片大小有限制，长宽任一超出 16383 像素，则不能使用 webp 进行编码。少数长文截图可能会超出这个限制。

**Comment by 2019ncovmemory** [comment]
我们已使用graphicsmagick将png转换成jpg，图片体积应该有大幅减少，阅读体验无明显变化。
