### ISSUE TITLE
分享几篇文章 感谢编选小组的各位

### ISSUE THREAD

**Issue by nishiki1029** [2019ncovmemory/nCovMemory#5]
新的档案太美观易用了T_T感恩。
分享几篇文章，正好也是档案里未收录的媒体。各位可以看一下是否合适加入档案。各位辛苦啦！

**三声**
0131 我在医护出行互助群的72小时 | 武汉人①
https://mp.weixin.qq.com/s/Lj6Z0FIeAYWTaxpJZ3Vv7Q
0201 光谷的几位程序员，用七小时搭起医疗物资信息平台｜武汉人②
https://mp.weixin.qq.com/s/gM5OMLoLawRTRNqK7DKlaQ
0204 被家乡推开的人 | 武汉人③
https://mp.weixin.qq.com/s/XC4M2XxoCQ9qoDv9Ry-eaA

**中国经营报**
0205 拉医生的武汉“司机们”：约好了“战后”酒局却不知彼此长相丨新冠肺炎亲历
https://mp.weixin.qq.com/s/6zafNJ4_ko4ytGWTv8pgdQ
0205 卖菜、扔菜、闭店 疫情影响下的京城餐饮
https://mp.weixin.qq.com/s/dmm5iWN-jHEkLGevr1hcjA

**界面**
0205 疫情下创业者艰难自救：仿佛突然被按下了暂停键
https://mp.weixin.qq.com/s/NyfeQt2F5-pr7-TkslvEHA

**极昼工作室**
0205 武汉外卖员穿过人间烟火
https://mp.weixin.qq.com/s/dSxAds83d2Vkxi85tFXOOA
0204 从确诊到康复，一个医学研究生的生死10天
https://mp.weixin.qq.com/s/N1jDooSKnf2dJrDaHoqCWA
0131 湖北女孩回村记
https://mp.weixin.qq.com/s/FHcS57yGDp_JCFIMDRoQew
0130 生下儿子后，大年初一我确诊了新冠肺炎
https://mp.weixin.qq.com/s/Ph_x17sVqMPMlTYKaMztHg
0129 武汉“封城”后，志愿者车队故事
https://mp.weixin.qq.com/s/35gyjt_RCOzheSWcZ7D7uQ
0128 流浪的武汉人
https://mp.weixin.qq.com/s/8mm7kFsnuqIDwUfOm7PVIw
0127 肺炎疫情下的TR188航班全员隔离事件
https://mp.weixin.qq.com/s/GVMCUk7Za4R90KLsc_I1ag
0126 疫情之前，野味饕餮
https://mp.weixin.qq.com/s/ShfcCcQQaXOXmGglIoR7dQ

**谷雨实验室**
0204 90后外卖员拍摄城市日记：希望武汉早点好起来｜谷雨
https://mp.weixin.qq.com/s/1B7gwVKY8aoPRvhcdCC2Bg
0202 武汉，当一群摇滚青年加入紧急救援｜谷雨
https://mp.weixin.qq.com/s/ASHJ2RX7fGf7HYuC2Vk-5Q
0201 突然被延期开学击中的父母｜谷雨
https://mp.weixin.qq.com/s/KjkYqFEM_De8q3LddOZo5A
0131 流落海外武汉人：我只想回家｜谷雨
https://mp.weixin.qq.com/s/BhP72wZBS9DqLX8IgTgr_A
0130 去留两难湖北人：我也不愿意连累任何人丨谷雨
https://mp.weixin.qq.com/s/eyjEBu4iby4d1f35SjcwCg
0130 湖北亲历者：我不希望再引起地域之争｜谷雨
https://mp.weixin.qq.com/s/T2MW5nPgEuR5rzMV2IdGAw
0129 上海亲历者：名古屋机场冲突始末丨谷雨
https://mp.weixin.qq.com/s/wuDd2py-bzZ1Yiq1G42pMA
0128 河南硬核防疫下的“武汉”归乡人丨谷雨
https://mp.weixin.qq.com/s/DbNrElRwx3Z_uSP0cSHabw

祝好！！
锦

**Comment by 2019ncovmemory** [comment]
親愛的nishiki1029,


來函敬悉，謝謝您的熱誠幫助，我們會加快採集與評估的速度。


關於您推薦的「騰訊新聞-谷雨實驗室」的內容，我們很遺憾地向您報告，該平台內容我們將暫不予收錄。原因是我們於前日夜晚收到該平台負責人郵件正式告知，不希望我們登載他們內容，理由是「審查環境惡劣」、「擔心部分海外人士曲解」，關於其內容，您可移步其網站或微信公眾號觀看。給您造成不便，萬分抱歉！


隨信送上整理平台的新連結 https://github.com/2019ncovmemory/nCovMemory，這個平台會收入原刊載於shimo
的鏈接、截圖和archive，在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀及幫助我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/5/20

>
