### ISSUE TITLE
[新文章]从1988年的30万人甲肝到新冠肺炎：上海是如何应对的？

### ISSUE THREAD

**Issue by syyuanjiahui** [2019ncovmemory/nCovMemory#50]
来源：三联生活周刊
标题：从1988年的30万人甲肝到新冠肺炎：上海是如何应对的？
日期：02-07 11:57
原始URL: https://mp.weixin.qq.com/s/LfrU1MAIse-XXhmcHSloXw
archive: https://archive.is/r5dsE
截图：
![1](https://user-images.githubusercontent.com/60779936/74029425-a56eda80-49e7-11ea-9936-e0a7f0a278e5.jpg)

**Comment by 2019ncovmemory** [comment]
谢谢推荐！此文现已收录。
