### ISSUE TITLE
截图更新：北青深一度《受训诫的武汉医生》

### ISSUE THREAD

**Issue by Nephiloso** [2019ncovmemory/nCovMemory#54]
北青深一度《受训诫的武汉医生》一文链接、截图、archive均失效，我这还存有此文的截图：

![mmexport1580143072642](https://user-images.githubusercontent.com/60774490/74054940-fb5c7600-4a19-11ea-82e7-f00f6988e8e9.jpeg)

**Comment by Nephiloso** [comment]
第一次用Github，不会打label，求教…

**Comment by 2019ncovmemory** [comment]
这一条已经收录过了～感谢！刚刚修好了一个bug，你再试一下可以了吗？label的话是手动加入的，在标题里。
