### ISSUE TITLE
README里面财经杂志《统计数字之外的人》两个往repo内链接失效

### ISSUE THREAD

**Issue by con-a** [2019ncovmemory/nCovMemory#57]
https://github.com/2019ncovmemory/nCovMemory/blob/master/data/non-fiction.csv#L74
这一行`screenshot`是
```
caijing-16A) [link](articles/caijing/caijing-16B.png
```
导致最后出来的README里面的link为：
```md
[link](/archive/png/caijing-16A) [link](articles/caijing/caijing-16B.png.png)
```

这两个链接第一个没有`.png`，第二个路径里面`caijing`应为`png`且有2个后缀。

`screenshot`应该是`caijing-16A.png) [link](articles/png/caijing-16B`，改一下应该就好。

**Comment by con-a** [comment]
看下来应该就这一篇有这个问题

**Comment by 2019ncovmemory** [comment]
已修复，感谢！
