### ISSUE TITLE
【新文章】澎湃新闻《“封堵武汉人”：从防疫话语到地方主义》

### ISSUE THREAD

**Issue by Etaicnune** [2019ncovmemory/nCovMemory#59]
【来源】澎湃新闻
【日期】2020-01-27 14:49
【标题】“封堵武汉人”：从防疫话语到地方主义
【作者】江序礼
【责编】伍　勤
【原始URL】https://www.thepaper.cn/newsDetail_forward_5650059
【Archive】https://web.archive.org/web/20200208080227/https://www.thepaper.cn/newsDetail_forward_5650059
【截图】
![newsDetail_forward_5650059-2](https://user-images.githubusercontent.com/38830687/74081882-b45c9800-4a8e-11ea-9714-999889ddd866.jpeg)

**Comment by Etaicnune** [comment]
【截图】
![newsDetail_forward_5650059-2](https://user-images.githubusercontent.com/38830687/74081826-27194380-4a8e-11ea-8da8-a31bf62b88c0.jpeg)

**Comment by 2019ncovmemory** [comment]
感谢推荐！但本站不收录分析类文章，欢迎您或网友自发整理！
