### ISSUE TITLE
看到了另外两份整理工作

### ISSUE THREAD

**Issue by nCovCover** [2019ncovmemory/nCovMemory#61]
疫情之下的劳动者--中文媒体报道收集（持续更新）
https://note.youdao.com/ynoteshare1/index.html?id=eee7c8c3d7b8b054dc94d8abd1a211d8&type=note

2020wuhan_individual_stories
来自豆友们在疫情期间的记录。暂定范围为豆瓣，未来可能有所扩增。
https://github.com/jiayiliujiayi/2020nCov_individual_archives?dt_dapp=1

**Comment by 2019ncovmemory** [comment]
多谢告知。已将您推荐的整理列入友情站点内。
