### ISSUE TITLE
【新文章】新民晚报《让公开透明的阳光刺破病毒雾障》

### ISSUE THREAD

**Issue by Estelle625** [2019ncovmemory/nCovMemory#62]
![image](https://user-images.githubusercontent.com/60812553/74083461-924e2000-4a64-11ea-9958-3e45d94e5763.png)

**Comment by 2019ncovmemory** [comment]
感谢推荐。遗憾的是，本站不收录评论类文章。我们认为评论文章一样亟需整理，欢迎您及网友自行整理，一起出一份力！
