### ISSUE TITLE
新文章|北青深一度|被声讨的“晋江毒王”：感到很抱歉，可我没撒谎 | 深度报道 

### ISSUE THREAD

**Issue by Elainexin** [2019ncovmemory/nCovMemory#64]
被声讨的“晋江毒王”：感到很抱歉，可我没撒谎 | 深度报道 
北青深一度
2020-02-08
原始链接:https://mp.weixin.qq.com/s/bJH5M8ZH05x4OasdXiJ72w
archive: https://archive.is/UgYVA
截图：
![被声讨的晋江毒王 (1)](https://user-images.githubusercontent.com/29773606/74089669-a1879a80-4a71-11ea-9f53-5fb7b6fd23a7.png)

**Comment by 2019ncovmemory** [comment]
感谢！我们已使用此文。
