### ISSUE TITLE
新文章|《财新周刊》2020年第5期封面报道|抢救新冠病人

### ISSUE THREAD

**Issue by Gnothi-Seauton** [2019ncovmemory/nCovMemory#67]
原标题：抢救新冠病人

现标题：四大ICU主任详解病毒 来自最前线的防治之策

源链：http://weekly.caixin.com/2020-02-07/101512870_all.html

archive链（原标题）：https://web.archive.org/web/20200208110745/http://weekly.caixin.com/2020-02-07/101512870_all.html

archive链（现标题）：https://web.archive.org/web/20200209043141/http://weekly.caixin.com/2020-02-07/101512870_all.html

![caixin](https://user-images.githubusercontent.com/11039471/74098021-0ca69f00-4b4e-11ea-8c91-6f557c362be7.png)

**Comment by 2019ncovmemory** [comment]
已加入，感谢！
