### ISSUE TITLE
是否考虑添加普通人叙述

### ISSUE THREAD

**Issue by jiayiliujiayi** [2019ncovmemory/nCovMemory#7]
非患者或家属在疫情期间的叙述，比如封城日记之类。

参考链接：
[封城日记.阳光之下.2020.02.05](https://www.douban.com/note/751130634/)
[1月24日](https://www.douban.com/note/749979554/)
[湖北疫情之孝感封城日记一](https://www.douban.com/note/749993552/)
[朋克新年](https://www.douban.com/note/750002265/)  

可能存在的问题：
1. 真为待证  
2. 需要获取原作者授权

**Comment by 2019ncovmemory** [comment]
親愛的Jiayi,


來函敬悉，我們亦曾經積極考慮過這一可能。但微博上信息過多，部分亦難以分辨其真實性，且主要是我們人數過少，報導及見聞工作量本身已難堪重負，目前僅能負擔現有的工作任務。如此情況，還望您能諒解！


但也請不要失望，我們亦有留意到部分類似志趣的人及團體在做您關注的整理，特此轉送給您：
https://shimo.im/docs/onq7MwVO6pf4FjA9/read


我們亦加快了搭建新站點的速度。現在，我們很高興地宣布，新的整理平台
https://github.com/2019ncovmemory/nCovMemory，這個平台在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/6/20

**Comment by jiayiliujiayi** [comment]
> 親愛的Jiayi, 來函敬悉，我們亦曾經積極考慮過這一可能。但微博上信息過多，部分亦難以分辨其真實性，且主要是我們人數過少，報導及見聞工作量本身已難堪重負，目前僅能負擔現有的工作任務。如此情況，還望您能諒解！ 但也請不要失望，我們亦有留意到部分類似志趣的人及團體在做您關注的整理，特此轉送給您： https://shimo.im/docs/onq7MwVO6pf4FjA9/read 我們亦加快了搭建新站點的速度。現在，我們很高興地宣布，新的整理平台 [https://github.com/2019ncovmemory/nCovMemory，這個平台在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：](https://github.com/2019ncovmemory/nCovMemory%EF%BC%8C%E9%80%99%E5%80%8B%E5%B9%B3%E5%8F%B0%E5%9C%A8%E9%95%B7%E5%9F%8E%E5%85%A7%E5%A4%96%E7%9A%86%E5%8F%AF%E9%96%8B%E5%95%9F%EF%BC%8C%E6%AD%A1%E8%BF%8E%E5%BB%A3%E5%82%B3%EF%BD%9E%E5%85%88%E5%89%8D%E7%9A%84shimo%EF%BC%88%E5%A0%B1%E5%B0%8E%EF%BC%9A) https://shimo.im/docs/2d05dce1eaa743c7 《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞： https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic ；報導： https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic ；）亦會持續更新，可保持關注～ 謝謝您的來信，也感謝您閱讀我們的整理！ Franklin Han 親歷者自述整理團隊成員 2/6/20
> […](#)

谢谢！
