### ISSUE TITLE
「新文章」2月8-9日的一些更新

### ISSUE THREAD

**Issue by y-soarrr** [2019ncovmemory/nCovMemory#71]
按列表更新了一些文章，新加了2月8日端传媒上的一篇来信。为避免辛苦的朋友重复劳动，先放上档案和原链接，图包稍后发

**端传媒**
标题：实习医生来信：致每一位在疫区中生活的香港人
日期：2020年02月08日 
原始URL：https://theinitium.com/article/20200209-notes-letter-from-houseman/
archive：https://archive.is/VxtCQ

**财新网**
标题：特写|封城半月后的武汉与湖北
日期：2020年02月09日 08:23 
原始URL：http://www.caixin.com/2020-02-09/101513229.html
Archive：https://archive.is/RRdQo

标题：肺炎日记|元宵节：武汉周边地区承压 全国医护人员增援
日期：2020年02月09日 08:06
原始URL：http://china.caixin.com/2020-02-09/101513225.html
Archive：https://archive.is/nhxYP

标题：孝感确诊病例增至湖北第二 市长称进入“平缓平台期”
日期：2020年02月09日 10:07
原始URL：http://china.caixin.com/2020-02-09/101513251.html
Archive:  https://archive.is/GbVYW

标题：封面报道|四大ICU主任详解病毒 来自最前线的防治之策
日期： 《财新周刊》2020年第5期 出版日期 2020年02月10日 
原始URL：http://weekly.caixin.com/2020-02-07/101512870.html
Archive: https://archive.is/EESHV

标题：解药|关注利巴韦林:第五版新冠诊疗方案修正用药剂量
日期：2020年02月09日 13:30
原始URL：http://china.caixin.com/2020-02-09/101513290.html
Archive:  https://archive.is/DcqKu

标题：民用口罩厂关停还是增产？仙桃市和湖北省政策不一
日期：2020年02月09日 13:03
原始URL：http://www.caixin.com/2020-02-09/101513277.html
Archive:  https://archive.is/SeTMb

**故事fm**
标题：声音日记：天气晴，今天是我染上新冠肺炎的第 8 天
日期：2020年02月09日 16:04
原始URL：https://mp.weixin.qq.com/s/PGsEXml6rmgpjafdEDWZ8g
Archive:  https://archive.is/30yqj

**南方都市报**
标题：李文亮妻子发声
日期：2020年02月08日 18:50
原始URL：https://mp.weixin.qq.com/s/OIN4PkRtyd6vFL4cPBZGYg
 Archive:  https://archive.is/uEMng

标题：援汉医生致相恋10年女友：万一我有意外，你可有其他选择
日期：2020年02月08日 23:40
原始URL：https://mp.weixin.qq.com/s/zb28TsrfpyPP8UzwXf8uZA
 Archive:  https://archive.is/HUErV

标题：一家6口5人确诊！今天，2岁宝宝终于见到了妈妈
日期：2020年02月08日 23:40
原始URL：https://mp.weixin.qq.com/s/TtmDHNiy4H0-7EAwVTiVYA
 Archive:  https://archive.is/sHV9v

**女孩别怕**
标题：边境线上测体温、每天接诊40余囚犯：疫情不耽误我上班
日期：2020年02月05日 14:59
原始URL：https://mp.weixin.qq.com/s/S7wmMRp34EKOBwsHyTtRHw
 Archive:  https://archive.is/hm8Pv

标题：武汉协和医生：我从没穿过这么贵的防护服
日期：2020年02月08日 11：28
原始URL：https://mp.weixin.qq.com/s/3nuGeMwtdPZUmu7Qgo73_g
 Archive:  https://archive.is/nJPec

标题：我是个武汉「逃兵」，我是个卑鄙的人吗？
日期：2020年02月09日 11：25
原始URL：https://mp.weixin.qq.com/s/vmkZsDpMgUV9Gbz5LhaRGQ
 Archive:  https://archive.is/9g2R7

**人物**
标题：在高速公路上漂流
日期：2020年02月09日 13：04
原始URL：https://mp.weixin.qq.com/s/4i9y3fyvnzdaitDdNn5Pyw
 Archive:  https://archive.is/ToCFg

**三联生活周刊**
标题：疫情之下，快手里守望时刻
日期：2020年02月08日 21：16
原始URL：https://mp.weixin.qq.com/s/s61rYJQTAR9r7hB2lP1xzg
 Archive:  https://archive.is/QTsdu

标题：今天元宵节，我却想吃炸鸡
日期：2020年02月08日 21：16
原始URL：https://mp.weixin.qq.com/s/CTxu-ghVEIDKXw1bJ9xMsQ
 Archive:  https://archive.is/IzhYY

**腾讯科技**
标题：美籍华人艰难返美回家路：美联航不让登机 有人落地后被关小黑屋
日期：2020年02月08日 
原始URL：https://mp.weixin.qq.com/s/ubdlnw7Xi2-Uml2ORZIxTg
 Archive:  https://archive.is/Na8TJ

标题：6000武汉网约车司机“敢死队”：冒险接医生送物资，瞒着家人报名
日期：2020年02月08日 
原始URL：https://mp.weixin.qq.com/s/nqHk5mz17uG7rrxoDun-uA
Archive:  https://archive.is/zK1yl

**新京报**
标题：呼吁允许快递外卖小哥进小区，“无接触配送”对防疫更为有利
日期：2020-02-09 02:30:07
原始URL：http://www.bjnews.com.cn/opinion/2020/02/09/686554.html
 Archive:  https://archive.is/y9zpD

标题：援助湖北医疗队员视频见证儿子出生：希望以后能加倍补偿
日期：2020-02-08 18:23:21
原始URL： http://www.bjnews.com.cn/feature/2020/02/08/686428.html
Archive:  https://archive.is/cluX0

标题：退伍军人自驾到“雷神山”工地报名：我们干的，不值一提
日期：2020-02-08 22:47:25
原始URL： http://www.bjnews.com.cn/feature/2020/02/08/686524.html
Archive:  https://archive.is/WP3Be

标题：无处化疗的肿瘤患者：本地医院接收困难，外地就医路被封
日期：2020-02-09
原始URL： https://mp.weixin.qq.com/s/GTPNRDCppF77W43WI2M82Q
Archive:  https://archive.is/NeD56

**一条**
标题：疫情爆发之初，一对武汉母女的生死20天
日期：2020-02-09
原始URL： https://mp.weixin.qq.com/s/gTVDbZD3Lot6F9Pap2La2w
Archive:  https://archive.is/OC8l1

**单读**
标题：一个“北漂”的武汉人决定搬家丨编辑观察
日期：2020-02-07 08：30
原始URL： https://mp.weixin.qq.com/s/zN-L-oZiAXSNcCiuc6bRPg
Archive:  https://archive.is/PnbfE

标题：危难时刻你们怎么还关在象牙塔里丨单读
日期：2020-02-07 08：30
原始URL：https://mp.weixin.qq.com/s/VJIXoL5Y5KB7vwJIz7-zcQ
Archive:  https://archive.is/kXKEO

标题：绝望是一场夜战丨公开信
日期：2020-02-09 09：30
原始URL： https://mp.weixin.qq.com/s/ATHrwkq6kLWAHqkpm67YFA
Archive:  https://archive.is/Nqk1T

**阑夕**
标题：武汉封城日记｜第十七天
日期：2020-02-08
原始URL： https://mp.weixin.qq.com/s/bnzFZDVIzrWlxU3pcjE-Mw
Archive:  https://archive.is/dNBnA

**Comment by y-soarrr** [comment]
issue#46图包链接：https://photos.app.goo.gl/vSbUw3izpQZvBD6f9

**Comment by 2019ncovmemory** [comment]
多谢补充！经筛选后，多数文章我们已经补入。希望您继续支持本站~
