### ISSUE TITLE
2020我的封城时光

### ISSUE THREAD

**Issue by wildfireXwind** [2019ncovmemory/nCovMemory#72]
这是一名武汉医生的个人叙述文章
标题：2020我的封城时光
日期：2020.02.06
原始链接：[https://www.meipian.cn/2ocloxax](https://www.meipian.cn/2ocloxax)
archive：[https://web.archive.org/web/20200209110043/https%3A%2F%2Fwww.meipian.cn%2F2ocloxax](https://web.archive.org/web/20200209110043/https%3A%2F%2Fwww.meipian.cn%2F2ocloxax)

**Comment by 2019ncovmemory** [comment]
感谢！此文将在下次更新时收入。
