### ISSUE TITLE
火神山医院完工之后|一位建设工人的返乡纪实

### ISSUE THREAD

**Issue by jiayiliujiayi** [2019ncovmemory/nCovMemory#73]
标题：火神山医院完工之后|一位建设工人的返乡纪实    
日期：2020年02月09日  
原始链接：http://lanxuan.blog.caixin.com/archives/221180

**Comment by eyesvot** [comment]
截图呢？

**Comment by jiayiliujiayi** [comment]
> 截图呢？

截图：
![](https://raw.githubusercontent.com/jiayiliujiayi/jiayitest/master/1.png)
![](https://raw.githubusercontent.com/jiayiliujiayi/jiayitest/master/2.png)

**Comment by wei1224hf** [comment]
The blog's URL is 404 now , it's deleted

**Comment by wei1224hf** [comment]
The bolg is deleted

**Comment by 2019ncovmemory** [comment]
感谢！此文将于下次更新时收入。

**Comment by jiayiliujiayi** [comment]
> 感谢！此文将于下次更新时收入。

谢谢，辛苦了！
