### ISSUE TITLE
端传媒

### ISSUE THREAD

**Issue by mengyyy** [2019ncovmemory/nCovMemory#8]
https://t.me/mengyshare/3507
https://telegra.ph/2020-02-05-疫区日记在撤侨选择前我决定留在武汉与父母相伴-02-05

https://t.me/mengyshare/3505
https://telegra.ph/2020-02-05-从武汉返乡后他们被泄露隐私被警察铐走被酒店驱赶-02-04

https://t.me/mengyshare/3491
https://telegra.ph/2020-02-02-疫区日记疫情蔓延时我回到湖北家乡-02-02

**Comment by 2019ncovmemory** [comment]
親愛的mengyyy,


來函敬悉，謝謝您的熱誠幫助，我們會加快採集與評估的速度。


我們認為，從門類上講，端傳媒業務遍及兩岸三地，是獨特的存在，不應被收入「內地傳媒」。此外，比較重要的一點是，端傳媒設置了付費閱讀機制，出於尊重其成果及版權的需要，我們更推薦讀者循正常途徑付費閱讀他們的辛苦成果。


而且，我們的工作目前是儘量收錄一些刊發於大陸平台上的、有被當局刪除/刻意忽略之可能的文章，可以理解為「備份」。基於以上原因，我們暫時不會收錄端傳媒涉及是次事件的，但依然感謝您的推薦！


隨信送上整理平台的新連結 https://github.com/2019ncovmemory/nCovMemory，這個平台會收入原刊載於shimo
的鏈接、截圖和archive，在長城內外皆可開啟，歡迎廣傳～先前的shimo（報導：
https://shimo.im/docs/2d05dce1eaa743c7

《新冠肺炎：传媒报道和非虚构写作（持续更新）》）、google drive（見聞：
https://docs.google.com/document/u/1/d/1lpZ-4BiuG6KRW5LgcN6S3E-9XYlHP0pSI58kGTxYzWo/mobilebasic
；報導：
https://docs.google.com/document/u/1/d/1EQndEHB0gNlNWY1J5cwI_IT3u-1RP3UJJyzURotwqvk/mobilebasic
；）亦會持續更新，可保持關注～


謝謝您的來信，也感謝您閱讀及幫助我們的整理！


Franklin Han

親歷者自述整理團隊成員

2/6/20
