### ISSUE TITLE
[新文章]《李文亮医生的最后40天》

### ISSUE THREAD

**Issue by ocavue** [2019ncovmemory/nCovMemory#81]
日期：2020-02-09 

作者：财经十一人

> 由《财经》杂志公司产业报道团队创建，研讨企业成败，探究行业兴衰，推动阳光商业

原始链接：

- [微信公众号](http://mp.weixin.qq.com/s?__biz=MzI0MjU2NTA1Mg==&amp;mid=2247494555&amp;idx=2&amp;sn=6e159e9a148d2d78e77a719772e0b2de&amp;chksm=e978c148de0f485e8b459a1a5c395d3b1ddf40501e68af8edd0cbcc45f9dbaa48b1b7fe74211)

转载链接：
- [wemp.app](https://wemp.app/posts/c29f1724-2984-49dc-a019-56c52e63c2e8?utm_source=bottom-latest-posts)
- [微博文章](https://weibo.com/ttarticle/p/show?id=2309404470450435522649)

archive: https://archive.is/Tupjw

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文将于下次更新时收入。
