### ISSUE TITLE
剥洋葱people 1月30日报道的链接和截图有误

### ISSUE THREAD

**Issue by edwardchanswatow** [2019ncovmemory/nCovMemory#82]
剥洋葱people 1月30日报道的链接和截图有误。
题目：0130-武汉某定点医院被隔离的医生：曾一晚接诊200名患者
链接：https://mp.weixin.qq.com/s/W5_q5hIl2TXKjkwKPQj0Ng
截图：
![0130-武汉某定点医院被隔离的医生：曾一晚接诊200名患者](https://user-images.githubusercontent.com/60776454/74144204-456e7300-4c37-11ea-8dda-35797470ab2b.png)

**Comment by 2019ncovmemory** [comment]
感谢指出，已更新。
