### ISSUE TITLE
[新文章]一篇针对中小微企业在疫情中面临困境的文章

### ISSUE THREAD

**Issue by musicoooool** [2019ncovmemory/nCovMemory#88]
- **日期：** 2020-02-10
- **作者：** 我为国言吴海

> 魅KTV投资人，桔子水晶酒店、桔子酒店创始人，业余投资人，a rational patriot

- **原始链接：**  [哎，我只是个做中小微企业的](https://mp.weixin.qq.com/s/AGyajv8Qm0kaMLcFU62huQ)
- **archive:** [http://archive.ph/wip/LrVvN](http://archive.ph/wip/LrVvN)

**Comment by 2019ncovmemory** [comment]
感谢推荐！此文将于下次更新时收录。
