### ISSUE TITLE
[新闻章]口述 | 湖北省作协主席李修文：我的心是乱的，现在没法写作

### ISSUE THREAD

**Issue by lingjzhu** [2019ncovmemory/nCovMemory#89]
日期： 2020-02-10
作者： 李修文、何映宇
媒体：新民周刊
原始链接： [口述 | 湖北省作协主席李修文：我的心是乱的，现在没法写作](https://mp.weixin.qq.com/s/8Lx6M3qAzC8w35GEqyi6Og)
archive: http://archive.ph/C4wpi

**Comment by 2019ncovmemory** [comment]
此文今日更新将会加入。感谢！
