### ISSUE TITLE
[新文章]我是互联网人，我没有做逃兵

### ISSUE THREAD

**Issue by chuyaguo2014** [2019ncovmemory/nCovMemory#90]
- 日期：2月1日（不是非常确定哈）

- 标题：我是互联网人，我没有做逃兵

- 源链：https://mp.weixin.qq.com/s/AeSzGxJL1hHotcLGiruPIw

- archive链： https://archive.is/ziRgg

**Comment by chuyaguo2014** [comment]
不知道该怎么加label呀 - 貌似我权限不够？

**Comment by 2019ncovmemory** [comment]
多谢推荐！此文已收录。
