### ISSUE TITLE
《中国新闻周刊》相关报道（补充、待整理） #新文章#

### ISSUE THREAD

**Issue by lemonmissing** [2019ncovmemory/nCovMemory#93]
标题：“超级传播者”：他转移4次病房，传染了14名医护人员
日期：2020年01月25日 12:03
链接：https://mp.weixin.qq.com/s/Z8JSBuK_-hEweM_yG9KbBQ
archive：https://archive.is/V1OjN#selection-41.64-41.90

标题：武汉医生患病后自己诊治、隔离：我们的麻醉师插管没有护目镜，就用泳镜 
日期：2020年01月25日 22:41
原文链接：https://mp.weixin.qq.com/s/9zZF2OobjfrMK9-IV9wVWw
archive：https://archive.is/EAyMz

标题：实地探访武汉中南医院重症病房：“请不要为我担心” 
日期：2020年01月27日 20:11
原文链接：https://mp.weixin.qq.com/s/BHuyKnNUCGzh31h7wK_UsA
archive：https://archive.is/gq6fT

标题：被清空的武汉：一座没有陌生人的城市
日期：2020年01月29日 9:02
原文链接：https://mp.weixin.qq.com/s/7r7yDQfLqS8QQqVqGsheWw
archive：https://archive.is/rBOEn

标题：父亲来自黄冈传染病医院病房的最后一个电话：“好的，战斗吧”
日期：2020年02月01日 18:55
原文链接：https://mp.weixin.qq.com/s/kO-nx27_qnQCfMoeYLrS2Q
archive：https://archive.is/LIWAH

标题：武汉之憾:黄金防控期是如何错过的?
日期：2020年02月05日 
链接：http://eguojiribao.com/20554/    
（抱歉没有原文链接，公众号原文已经被删）
archive：https://archive.is/O7Td2

标题：封面调查 | 致命野味，非法盗猎和买卖为何屡禁不止？ 
日期：2020年02月05日 20:18
原文链接：https://mp.weixin.qq.com/s/pRFhxHZxmcblG--_6ke_zg
archive：https://archive.is/gXH6B

标题：李文亮去世10小时，国家监委决定赴武汉全面调查  
日期：2020年02月07日 13:55
原文链接：https://mp.weixin.qq.com/s/6NNgoiDdb3wUukKF3rAiIg
archive：https://archive.is/NH7l8

标题：武汉精神卫生中心院内感染，约80名医患确诊新冠肺炎
日期：2020年02月08日 21:50
原文链接：https://mp.weixin.qq.com/s/RZr9wYWFjGxZlnM7JBSm_g
archive：https://archive.is/reHST

**Comment by 2019ncovmemory** [comment]
感谢！我们已根据您的推荐补充文章。
