### ISSUE TITLE
老喻：病毒时期的生命的价值

### ISSUE THREAD

**Issue by ZZZ989** [2019ncovmemory/nCovMemory#94]
标题：老喻：病毒时期的生命的价值
日期：2020年02月11日
原始链接：http://tangya.blog.caixin.com/archives/221304
Archive: https://web.archive.org/save/http://tangya.blog.caixin.com/archives/221304

**Comment by 2019ncovmemory** [comment]
感谢推荐。但本站暂时不收录评论为主的文章，欢迎您和网友自己整理~
