### ISSUE TITLE
财新网报道更正

### ISSUE THREAD

**Issue by edwardchanswatow** [2019ncovmemory/nCovMemory#95]
0206-记者手记 疫情中的货车司机：每天只吃一顿饭  截图出错
![0206-记者手记 疫情中的货车司机：每天只吃一顿饭](https://user-images.githubusercontent.com/60776454/74297081-b8373580-4d80-11ea-94ca-65996910462e.png)

**Comment by edwardchanswatow** [comment]
0206-肺炎日记 2月5日：疫情不确定性增加，危重病人三周定生死 
表格标为2月4日，实际应为2月6日

**Comment by edwardchanswatow** [comment]
0205-【独家】石正丽回应质疑 专家一致认为新冠病毒非人造
链接有无  正确链接：http://www.caixin.com/2020-02-05/101511817.html
截图有误  截图
![0205-【独家】石正丽回应质疑 专家一致认为新冠病毒非人造](https://user-images.githubusercontent.com/60776454/74297176-ff252b00-4d80-11ea-8ed3-29d23cfd51c2.jpg)

**Comment by edwardchanswatow** [comment]
0205-解药 武汉病毒所陷争议：为何此时宣布申请瑞德西韦新用途专利？  截图有误
![0205-解药 武汉病毒所陷争议：为何此时宣布申请瑞德西韦新用途专利？ ](https://user-images.githubusercontent.com/60776454/74297197-13692800-4d81-11ea-8fe4-516f1556f34f.png)

**Comment by 2019ncovmemory** [comment]
感谢耐心指正！已全部更新，将于一日内更新至网页与readme。
