### ISSUE TITLE
这里适合存档一些纸媒的文章吗？

### ISSUE THREAD

**Issue by RtYkk** [2019ncovmemory/nCovMemory#97]
很多纸媒都出了专题。如果可以，就能用一些扫描/拍照/电子档的形式进行存档？但是是不是会牵涉到一些版权问题。

**Comment by nCovCover** [comment]
不知道可否请您提名一些纸媒呢？纸媒如果有新媒体平台的话，应该可以引用他们的链接，项目里也这样收录了一些，没有的话就不知道了……

**Comment by RtYkk** [comment]
> 不知道可否请您提名一些纸媒呢？纸媒如果有新媒体平台的话，应该可以引用他们的链接，项目里也这样收录了一些，没有的话就不知道了……

就比如说财新，有电子版的纸媒。但是是需要订阅付费的。大概和那些免费公开的文章有所区别。
[财新周刊第890期](http://weekly.caixin.com/2020/cw890/) 
[财新周刊第891期](http://weekly.caixin.com/2020/cw891/)

**Comment by nCovCover** [comment]
> 就比如说财新，有电子版的纸媒。但是是需要订阅付费的。大概和那些免费公开的文章有所区别。
> [财新周刊第890期](http://weekly.caixin.com/2020/cw890/)
> [财新周刊第891期](http://weekly.caixin.com/2020/cw891/)
> 再举一个三联生活周刊的例子
> [三联生活周刊第1074期](http://www.lifeweek.com.cn/magazine/lifeweek/2020/1121/)

平常的时候财新网上的报道都是有付费墙的，现在是疫情期间，他们才免费公开了这些报道，所有我猜大概是没有区别的？

**Comment by neosjasmin** [comment]
点进去还是要收费的。。

**Comment by RtYkk** [comment]
仔细考虑了一下，关了吧。昨天我第七期三联到了，本来想扫个图。还是应该会有些版权问题
