### ISSUE TITLE
[新文章]冰点2.12文章

### ISSUE THREAD

**Issue by tzwang98** [2019ncovmemory/nCovMemory#98]
日期： 2020-02-12
作者： 秦珍子
媒体：冰点周刊
原始链接：https://mp.weixin.qq.com/s/pLMkpaaNmV2WxfmKS9upQQ

日期： 2020-02-12
作者： 采访 |   王梦影  杨 杰  魏 晞  秦珍子  马宇平 主笔 | 张 国
媒体：冰点周刊
原始链接：https://mp.weixin.qq.com/s/gloNzBrX-1mSlZbSbGYEfQ

**Comment by tzwang98** [comment]
不好意思没看到怎么打label，是只有项目管理者才可以吗

**Comment by 2019ncovmemory** [comment]
谢谢！文章将于下次更新时收入。
